[package]
name = "netgame"
version = "0.1.0"
authors = ["rasmussn <rasmussn@kth.se>", "vstenm <vstenm@kth.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5"
chrono = "0.4"

